name: e2e (Experimental)
on:
  push:
    branches: ["feature/add-e2e-action"]
  workflow_dispatch:
    branches: ["feature/add-e2e-action"]
jobs:
  powerdns-e2e:
    name: E2E tests for powerdns
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repository
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: build-powerdns
        run: make build-powerdns
      - name: e2e-test
        uses: ivancorrales/newrelic-integration-e2e-action@master
        with:
          spec_path: exporters/powerdns/e2e_spec.yml
          license_key: ${{ secrets.LICENSE_KEY }}
          verbose: true


