
name: Release

on:
  release:
    types: [edited]

jobs:
  publish-to-s3:
    name: Send release assets to S3
    runs-on: ubuntu-20.04
    steps:
      - id: release_details
        run: |
          echo "1"
          integration=${{ github.event.release.name}}
          echo "2"
          integration=${integration% *}
          echo "3"
          echo "${integration}"
          echo "4"
          echo "::set-output name=integration::${integration}"
          echo "5"

          version=$(echo ${{ github.event.release.name}})
          version=$(echo ${version#* })
          echo "::set-output name=version::${version}"

          isPrerelease=$(echo ${{ github.event.release.prerelease }})
          echo "::set-output name=isPrerelease::${isPrerelease}"

      - run: echo "${{ steps.release_details.outputs.integration }}
      - run: echo "${{ steps.release_details.outputs.version }}
      - if: ${{ steps.release_details.outputs.isPrerelease == 'true'}}
        run: echo "Is prerelease"
      - if: ${{ steps.release_details.outputs.isPrerelease != 'true'}}
        run: echo "Is NOT prerelease"