
name: Release

on:
  release:
    types: [published]

jobs:
  publish-to-s3:
    name: Send release assets to S3
    runs-on: ubuntu-20.04
    steps:
      - run: echo "${github.event.release}"
        