
name: Release

on:
  release:
    types: [updated]

jobs:
  publish-to-s3:
    name: Send release assets to S3
    runs-on: ubuntu-20.04
    steps:
      - run: echo "${{ github.event.release.tag_name }}"
      - run: echo "${{ github.event.release.prerelease }}"
      - run: echo "${{ github.event.release.name }}"
